-- Daha dolu vitrin: indirim dağılımı, Türkçe ürün isimleri, ek katalog, kampanyalar, demo yorumlar

-- Öne çıkanlar (discount > 20) ve indirim köşesi (discount > 0) için yeterli ürün
UPDATE products
SET discount = 22 + (abs(hashtext(id::text)) % 25)
WHERE is_active = TRUE AND discount <= 20 AND id % 3 = 0;

UPDATE products
SET discount = 5 + (abs(hashtext((id + 7)::text)) % 20)
WHERE is_active = TRUE AND discount = 0 AND id % 2 = 0;

-- "Katalog ####" satırlarını gerçekçi Türkçe pazaryeri ürün adlarına çevir
UPDATE products AS p
SET
    product_name = v.pname,
    description = v.pdesc
FROM (
    VALUES
        (0, 'Samsung Galaxy A54 5G 128 GB Akıllı Telefon', 'AMOLED ekran, 50 MP kamera, 5000 mAh pil, Android 14.'),
        (1, 'Apple iPhone 15 128 GB Mavi', 'A16 Bionic, Dynamic Island, çift kamera, 5G desteği.'),
        (2, 'Xiaomi Redmi Note 13 Pro 256 GB', '120 Hz AMOLED, 200 MP ana kamera, hızlı şarj.'),
        (3, 'Dyson V15 Detect Kablosuz Süpürge', 'Lazer toz tespiti, akıllı ekran, güçlü emiş.'),
        (4, 'Arçelik 6144 Buzdolabı No Frost', 'A++ enerji, çoklu hava kanalı, LED aydınlatma.'),
        (5, 'Philips Airfryer XXL 7.2 L', 'Yağsız pişirme, 7 program, kolay temizlik.'),
        (6, 'Nike Air Max 270 Erkek Spor Ayakkabı', 'Gün boyu konfor, hava yastığı, nefes alır üst.'),
        (7, 'Adidas Ultraboost 22 Koşu Ayakkabısı', 'Boost taban, Primeknit üst yüzey, yol koşusu için.'),
        (8, 'Levi''s 501 Original Fit Kot Pantolon', 'Klasik kesim, %100 pamuk, uzun ömürlü denim.'),
        (9, 'Koton Oversize Kadın Tişört', 'Yumuşak penye, günlük kombinler için ideal.'),
        (10, 'Karaca Biogranit 7 Parça Tencere Seti', 'Yapışmaz yüzey, indüksiyon uyumlu, kapaklı.'),
        (11, 'JBL Flip 6 Taşınabilir Bluetooth Hoparlör', 'IP67 su geçirmez, 12 saat çalma, güçlü bas.'),
        (12, 'Sony WH-1000XM5 Kulak Üstü Kulaklık', 'Endüstri lideri gürültü engelleme, 30 saat pil.'),
        (13, 'Logitech MX Master 3S Kablosuz Mouse', 'Sessiz tıklama, çoklu cihaz, ergonomik.'),
        (14, 'LG 55" 4K UHD Smart TV', 'webOS, HDR, ince çerçeve, oyun modu.'),
        (15, 'Bosch Serie 6 Ankastre Fırın', 'Pirolitik temizlik, 3D sıcak hava, dokunmatik.'),
        (16, 'Fissler Vitaquick Düdüklü Tencere 6 L', 'Güvenlik sistemi, paslanmaz çelik, tüm ocaklar.'),
        (17, 'Stanley Termos 1.18 L', '24 saat sıcak/soğuk, paslanmaz çelik, kamp ve ofis.'),
        (18, 'The North Face Ceket Erkek', 'Su itici, rüzgara dayanıklı, hafif dolgu.'),
        (19, 'Columbia Outdoor Bot', 'Kaymaz taban, su geçirmez membran, trekking.'),
        (20, 'IKEA MALM 160x200 Karyola', 'Minimal tasarım, yan çekmeceler, beyaz/ meşe seçenek.'),
        (21, 'English Home Çift Kişilik Nevresim Takımı', '%100 pamuk ranforce, yüksek iplik sayısı.'),
        (22, 'L''Oreal Paris Nem Terapisi Yüz Kremi', 'Hyaluronik asit, günlük nemlendirme, tüm ciltler.'),
        (23, 'Maybelline Sky High Maskara', 'Hacim ve uzunluk, suya dayanıklı seçenek.'),
        (24, 'Lego Technic Yarış Arabası Seti', '10+ yaş, mekanik parçalar, STEM eğlencesi.'),
        (25, 'Barbie Dreamhouse 3 Katlı Oyun Evi', 'Aksesuarlar dahil, geniş oyun alanı.'),
        (26, 'Castrol Edge 5W-30 Motor Yağı 4 L', 'Tam sentetik, uzun değişim aralığı, API onaylı.'),
        (27, 'Michelin CrossClimate+ 205/55 R16 4 Mevsim', 'Yüksek kilometre, ıslak zeminde fren.'),
        (28, 'Huawei MatePad 11.5 Tablet', '120 Hz ekran, çoklu pencere, stylus uyumlu.'),
        (29, 'Lenovo IdeaPad Slim 3 i5 16GB 512GB SSD', 'Günlük iş ve ders için ince laptop, Windows 11.'),
        (30, 'Tefal Titanium Ingenio Tava Seti', 'Çıkarılabilir sap, fırına uygun, 3 parça.'),
        (31, 'Sinbo Elektrikli Çay Makinesi', 'Çift demlik, otomatik kapanma, cam hazne.'),
        (32, 'Fakir Ranger Elektrikli Süpürge', 'Toz torbasız, HEPA filtre, park modu.'),
        (33, 'Pierre Cardin Erkek Deri Cüzdan', 'RFID korumalı, çoklu kart gözü, hediye kutulu.'),
        (34, 'Guess Kadın Kol Saati', 'Paslanmaz çelik, mineral cam, şık tasarım.'),
        (35, 'Casper Excalibur G770 Oyuncu Laptopu', 'RTX ekran kartı, yüksek TGP, RGB klavye.'),
        (36, 'Rampage Oyuncu Mouse Pad XXL', 'Dikişli kenar, kaymaz taban, düz yüzey.'),
        (37, 'Lipton Yellow Label 100''lü Demlik Poşet Çay', 'Geleneksel lezzet, ekonomik paket.'),
        (38, 'Ülker Çikolatalı Gofret 24''lü Paket', 'Atıştırmalık, okul ve ofis için.'),
        (39, 'Persil Toz Deterjan 9 kg', 'Beyaz ve renkliler, leke çıkarıcı etki.'),
        (40, 'Prima Premium Care Bebek Bezi 5 Beden', 'Yüksek emicilik, cilt dostu, ekonomik jumbo.'),
        (41, 'Johnson''s Baby Şampuan 500 ml', 'Göz yakmayan formül, hassas cilt için.'),
        (42, 'Karcher K4 Basınçlı Yıkama Makinesi', 'Ev ve araç yıkama, hortum ve tabanca dahil.'),
        (43, 'Gardena Hortum Seti 20 m', 'Spray tabanca, bağlantı parçaları, UV dayanımı.'),
        (44, 'Moleskine Classic Not Defteri A5', 'Sert kapak, lastikli, arka cep.'),
        (45, 'Faber-Castell 120''li Kuru Boya Kalemi', 'Yumuşak uç, karıştırma için ideal.'),
        (46, 'Havit Mekanik Klavye RGB', 'Outemu switch, tam boy, oyun ve yazım.'),
        (47, 'Rampage SMX-R17 Mikrofon Seti', 'Streamer ve toplantı için, ayaklı ve pop filtre.')
) AS v(mod48, pname, pdesc)
WHERE p.product_name LIKE 'Katalog %' AND mod(p.id, 48) = v.mod48;

-- Ek büyük katalog: 800 yeni ürün (Türkçe isimler, kategori dağılımı)
INSERT INTO products (
    product_name,
    unit_price,
    unit_in_stock,
    quantity_per_unit,
    category_id,
    description,
    image_url,
    discount,
    version,
    is_active
)
SELECT
    v.pname,
    ROUND((29.99 + random() * 420)::numeric, 2),
    (8 + floor(random() * 120))::int,
    '1 adet',
    1 + ((g.n - 1) % 18),
    v.pdesc,
    'https://picsum.photos/seed/tm' || g.n || '/400/300',
    CASE WHEN random() < 0.42 THEN (12 + floor(random() * 35))::int ELSE 0 END,
    0,
    TRUE
FROM generate_series(1, 800) AS g(n)
CROSS JOIN LATERAL (
    SELECT *
    FROM (
        VALUES
            ('Emsan Steel Pro Çelik Tencere 20 cm', 'Paslanmaz çelik, cam kapak, tüm ocak türleri.'),
            ('Korkmaz A153 Granit Tava 26 cm', 'Yapışmaz granit kaplama, ergonomik sap.'),
            ('Schafer Alüminyum Düdüklü 7 L', 'Güvenlik valfi, ekonomik aile boyu.'),
            ('Fakir Kaave Türk Kahvesi Makinesi', 'Bol köpük, otomatik kapanma, 4 fincan.'),
            ('Arzum Okka Minio Türk Kahvesi', 'Kompakt tasarım, dokunmatik kontrol.'),
            ('Philips Daily Collection Tost Makinesi', 'Geniş yuvalar, ısı ayarı, kolay temizlik.'),
            ('Vestel CMI 97102 G Ankastre Mikrodalga', 'Grill fonksiyon, siyah cam panel.'),
            ('Grundig HD 5680 Saç Kurutma Makinesi', 'İyon teknolojisi, 2200 W, difüzör dahil.'),
            ('Braun Series 3 Tıraş Makinesi', 'Islak/kuru, hassas tıraş, şarjlı.'),
            ('Oral-B Pro 3500 Şarjlı Diş Fırçası', 'Basınç sensörü, 3 mod, seyahat kutusu.'),
            ('Beurer Tansiyon Aleti Kol Tipi', 'Büyük ekran, 60 hafıza, WHO göstergesi.'),
            ('Omron M3 Comfort Tansiyon', 'Intelli Wrap manşon, hareket sensörü.'),
            ('Siemens EQ300 Tam Otomatik Kahve Makinesi', 'Espresso ve süt köpüğü, kompakt gövde.'),
            ('Delonghi Magnifica S Otomatik Kahve', 'Öğütücülü, cappuccino hazırlığı, bakım uyarısı.'),
            ('Vestel BM 401 Blender Seti', 'Doğrayıcı, ölçü kabı, 800 W motor.'),
            ('Arçelik K 3284 Çay Makinesi', 'Inox gövde, sıcak tutma, demlik uyarısı.'),
            ('Profilo BM 3081 Mikrodalga', 'Dijital panel, hızlı pişirme programları.'),
            ('Regal RCM 8911 Cam Kettle', '1.7 L, otomatik kapanma, ısı göstergesi.'),
            ('Fakir Rosie El Blender Seti', 'Çırpıcı ve doğrayıcı başlık, 600 W.'),
            ('Kiwi KSP 2410 Su Isıtıcısı', 'Paslanmaz gövde, 360° taban, filtre.'),
            ('Eca Niobe Lavabo Bataryası', 'Krom, su tasarruflu perlötör, 5 yıl garanti.'),
            ('Grohe Eurosmart Mutfak Bataryası', 'Alman mühendislik, seramik kartuş.'),
            ('Kale Banyo Duş Seti', 'Yağmur başlığı, el duşu, krom yüzey.'),
            ('Vitra S20 Klozet Takımı', 'Rimless, yavaş kapanır kapak, hijyenik.'),
            ('İşbir Yatak 160x200 Ortopedik', '7 bölge yay, orta sert, 10 yıl garanti.'),
            ('Yataş Blue Star Yaylı Yatak 150x200', 'Visco katman, hava kanalları, çift taraflı.'),
            ('İstikbal Monte Koltuk Takımı', '3+3+1, açılır mekanizma, kumaş seçenekleri.'),
            ('Bellona İmperial Yemek Masası', 'Cam üst, 6 sandalye, modern çizgiler.'),
            ('Çilek Genç Odası Çalışma Masası', 'Kitaplıklı, çekmeceli, ergen odası için.'),
            ('İkea MICKE Bilgisayar Masası', 'Kablo deliği, çekmece, kompakt ofis.'),
            ('Adidas Copa Pure.2 Krampon', 'Çim saha, suni çim uyumlu, bağcıklı.'),
            ('Nike Mercurial Vapor Club FG', 'Hafif üst, hız odaklı krampon.'),
            ('Puma Future Play Halı Saha Ayakkabısı', 'Çorap gibi oturuş, çoklu renk.'),
            ('Hummel Elıte Basketbol Ayakkabısı', 'Yüksek bilek desteği, zemin tutuşu.'),
            ('Lescon Erkek Eşofman Altı', 'Polyester, cep fermuarlı, spor ve günlük.'),
            ('Kinetix Kadın Yürüyüş Ayakkabısı', 'Hafif taban, nefes alır file, reflektör.'),
            ('Lumberjack Outdoor Erkek Bot', 'Su geçirmez, kışlık astar, vibram taban.'),
            ('Greyder Günlük Erkek Ayakkabı', 'Hakiki deri, ortopedik iç taban.'),
            ('Polaris Kadın Topuklu Ayakkabı', '9 cm topuk, rahat iç ped, ofis ve davet.'),
            ('Derimod Unisex Deri Kemer', 'Klasik tokalı, siyah/kahve seçenekleri.'),
            ('Mavi Jake Slim Fit Jean Erkek', 'Esnek denim, dar paça, mavi yıkamalar.'),
            ('Colin''s Kadın Mom Jean', 'Yüksek bel, vintage görünüm, pamuklu.'),
            ('Defacto Çocuk Polar Mont', 'Su itici, kapüşonlu, okul için.'),
            ('LC Waikiki Bebek Body 3''lü Set', '%100 pamuk, çıtçıtlı, 0-12 ay.'),
            ('Ebebek Chicco Mama Sandalyesi', 'Katlanır, tekerlekli, yıkanabilir örtü.'),
            ('Philips Avent Biberon Isıtıcı', 'Buharlı sterilizasyon, otomatik kapanma.'),
            ('Babyjem Portatif Mama Sandalyesi', 'Masa kenarına sabitleme, kompakt.'),
            ('Kraft Sigma Oto Koltuğu 9-36 kg', 'Isofix, yan darbe koruması, ECE R44.'),
            ('Maxi-Cosi Pearl 360 Döner Oto Koltuğu', '360° döner taban, yenidoğan minderi.'),
            ('Graco Pack N Play Park Yatak', 'Katlanır, tekerlekli, seyahat çantası.'),
            ('Fisher-Price Eğitici Köpekçik', 'Türkçe şarkılar, ışık ve ses, 6 ay+.'),
            ('Play-Doh 24 Renk Oyun Hamuru Seti', 'Güvenli formül, kalıplar dahil, yaratıcılık.'),
            ('Hot Wheels 20''li Araba Seti', 'Metal gövde, koleksiyonluk modeller.'),
            ('Hasbro Monopoly Klasik Kutu Oyunu', 'Aile oyun gecesi, Türkçe içerik.'),
            ('Mattel UNO Kart Oyunu', 'Wild kartlar, eğlenceli kurallar.'),
            ('Ravensburger 1000 Parça Puzzle', 'Yüksek baskı kalitesi, manzara teması.'),
            ('Canon EOS R50 Aynasız Fotoğraf Makinesi', 'APS-C sensör, vlog odaklı, kit lens.'),
            ('GoPro Hero 11 Black Aksiyon Kamera', '5.3K video, HyperSmooth, su altı kutusu.'),
            ('DJI Mini 3 Drone Fly More', '249 g altı, 4K video, uzun pil ömrü.'),
            ('Anker PowerCore 20000 mAh Powerbank', 'Hızlı şarj, çift USB-C, seyahat.'),
            ('Apple AirTag 4''lü Paket', 'Kayıp eşya bulma, UWB hassas konum.'),
            ('Samsung SmartTag2 Bluetooth İzleyici', 'IP67, UWB, anahtarlık deliği.'),
            ('Xiaomi Mi Robot Vacuum Mop 2 Pro', 'Lazer haritalama, 3000 Pa emiş, uygulama.'),
            ('Roborock Q7 Max+ Robot Süpürge', 'Otomatik boşaltma istasyonu, mop.'),
            ('Arçelik 6364 Bulaşık Makinesi', '8 program, A+++, sessiz çalışma.'),
            ('Beko BM 6046 Ankastre Bulaşık', '6 program, inox panel, yarım yük.'),
            ('Profilo BM 4230 E Bulaşık', 'Quick wash, tablet gözü, enerji tasarrufu.'),
            ('Vestel BM 4201 X Bulaşık Makinesi', 'AquaStop, gecikmeli başlatma, 14 kişilik.'),
            ('Siemens SN53HS60MT Bulaşık', 'Zeolith kurutma, Wi-Fi, sessiz program.'),
            ('Bosch SMS6HMI00T Bulaşık', 'Home Connect, VarioSpeed, A+++.'),
            ('Electrolux ESF9516LOX Bulaşık', 'AirDry, 6 program, inox.'),
            ('Candy CDPN 2D360PX Bulaşık', 'Wi-Fi, 9 program, ekonomik.'),
            ('Indesit DFE 1B19 X Bulaşık', 'A+ enerji, 5 program, kompakt.'),
            ('Vestel FR 6041 No Frost Buzdolabı', 'Çekmeceli dondurucu, LED, A++.'),
            ('Beko RCNE 560E40ZXPN Buzdolabı', 'NeoFrost çift devre, inox, geniş hacim.'),
            ('Arçelik 570561 EI Buzdolabı', 'Inverter kompresör, sebzelik, A+++.'),
            ('Profilo BD3056W2VV Buzdolabı', 'Cam kapak, dijital panel, no frost.'),
            ('Samsung RB38T600ESA Buzdolabı', 'SpaceMax, Metal Cooling, A++.'),
            ('LG GC-B509PZXZ Buzdolabı', 'DoorCooling+, LINEAR Cooling, inox.'),
            ('Grundig GKND 5300 Buzdolabı', 'Active Fresh, hızlı soğutma, A++.'),
            ('Altus AL 306 B Mini Buzdolabı', 'Ofis ve yurt için kompakt, tek kapak.'),
            ('Simfer SC 180 Buzdolabı', 'Ekonomik segment, 180 cm, beyaz.'),
            ('Vestel CM 5301 Ankastre Ocak', '4 göz gaz, cam yüzey, emniyet valfi.'),
            ('Beko HIMW 64225 SX Ankastre Ocak', 'Wok gözü, elektrik ateşleme, inox.'),
            ('Arçelik OCD 611 EI Ankastre Fırın', 'Multifonksiyon, analog saat, siyah cam.'),
            ('Profilo FRMA326 Ankastre Fırın', 'Turbo fan, 8 program, inox.'),
            ('Siemens HB534AER0 Ankastre Fırın', 'activeClean pirolitik, 3D sıcak hava.'),
            ('Bosch HBF534ES0Q Ankastre Fırın', 'EcoClean arka duvar, LED ekran.'),
            ('Electrolux KOFGH40TX Ankastre Fırın', 'SteamBake, pirolitik, dokunmatik.'),
            ('Candy FCP605X Ankastre Fırın', 'Wi-Fi, 70 L hacim, inox.'),
            ('Indesit IFW 6544 C IX Ankastre Fırın', 'Turbo grill, mekanik zamanlayıcı.'),
            ('Vestel AD 6002 Ankastre Davlumbaz', 'Dokunmatik, 3 hız, LED aydınlatma.'),
            ('Beko HCP 61310 I Ankastre Davlumbaz', 'Karbon filtre seçeneği, 60 cm.'),
            ('Arçelik P 12 YI Ankastre Davlumbaz', 'T şekil filtre, sessiz motor.'),
            ('Profilo DA6 120 Ankastre Davlumbaz', 'Inox, 3 güç kademesi, enerji A.'),
            ('Eca Niobe Eviye Bataryası', '360° döner çıkış, krom, garantili.'),
            ('Grohe Eurosmart Cosmopolitan Lavabo', 'Sıcaklık limiti, SmoothBody hatlar.'),
            ('Vitra Z-Line Klozet', 'Asma veya ayaklı montaj, Rim-Ex.'),
            ('Kale Banyo Duş Kabini 90x90', 'Temperli cam, tekerlekli kapı.'),
            ('İşbir Visco Yastık Ortopedik', 'Boyun desteği, yıkanabilir kılıf.'),
            ('Yataş Visco Therapy Yastık', 'Hava kanallı visco, alerji dostu.'),
            ('English Home Pamuklu Pike Takımı', 'Çift kişilik, yazlık, desenli.'),
            ('Taç Saten Nevresim Çift Kişilik', 'Yumuşak dokunuş, fermuarlı yastık.'),
            ('Karaca Fine Pearl 12 Kişilik Yemek Takımı', 'Porselen, bulaşık makinesi uyumlu.'),
            ('Kütahya Porselen 24 Parça Yemek Seti', 'Desenli, günlük kullanım, hediyelik.'),
            ('Paşabahçe 6''lı Meşrubat Bardağı', 'Borosilikat cam, ısıya dayanıklı.'),
            ('Lav 12''li Kahve Yanı Bardağı', 'Opak ve şeffaf seçenekler.'),
            ('Emsan Premium Çay Bardağı 6''lı', 'İnce porselen, zarif form.'),
            ('Koroplast Buzdolabı Poşeti Orta 30''lu', 'Kilitli fermuar, gıda saklama.'),
            ('Scotch Brite Mikrofiber Temizlik Bezi 3''lü', 'Toz ve cam için, yıkanabilir.'),
            ('Pril Bulaşık Tableti 100''lü', 'Parlaklık ve tuz bir arada, ekonomik.'),
            ('Ariel Pods 3''lü Kapsül 39 Yıkama', 'Leke çıkarıcı, renk koruma.'),
            ('Vanish Kosla Leke Çıkarıcı 1 L', 'Beyaz ve renkliler için ayrı formül.'),
            ('Finish Quantum Bulaşık Tableti 80''li', 'Parlaklık ve cam koruma.'),
            ('Cif Krem Temizleyici 500 ml', 'Mutfak ve banyo, mikro partiküller.'),
            ('Ajax Banyo Spreyi 750 ml', 'Kireç ve sabun kalıntısı, ferahlık.'),
            ('Mr Muscle Mutfak Temizleyici', 'Yağ çözücü, sprey başlık.'),
            ('Molped Ultra Ped Orta 20''li', 'Nefes alan yüzey, kanal teknolojisi.'),
            ('Kotex Gece Ped Uzun 16''lı', 'Ekstra emici, yan korumalar.'),
            ('Sleepy Natural Bebek Islak Mendil 90''lı', 'Parfümsüz, kapaklı paket.'),
            ('Uni Baby Islak Mendil 72''li', 'Aloe vera, hypoallerjenik.'),
            ('Sleepy Natural Külot Bez 4 Beden', 'Esnek bantlar, ıslaklık göstergesi.'),
            ('Molfix Premium Bebek Bezi 6 Beden', 'Omurga kanalı, yüksek emicilik.'),
            ('Huggies Islak Mendil 3x56', 'Dermatolojik test, kalın doku.'),
            ('Bebelac Gold 2 Devam Sütü 800 g', '6-12 ay, demir ve omega desteği.'),
            ('Aptamil 3 Devam Sütü 800 g', 'Prebiyotik lif, bağışıklık desteği.'),
            ('Hero Baby 2 Devam Sütü 400 g', 'Ekonomik boy, dengeli içerik.'),
            ('Eti Canga Çikolatalı Bar 36''lı Koli', 'Fındıklı, okul kantini için.'),
            ('Ülker Halley 24''lü Paket', 'Marshmallow ve bisküvi, atıştırmalık.'),
            ('Eti Burçak Bisküvi 10''lu Paket', 'Lif kaynağı, kahvaltı ve ara öğün.'),
            ('Ülker Çokokrem 400 g Kavanoz', 'Fındık kreması, kahvaltılık.'),
            ('Torku Süt 1 L Tam Yağlı', 'UHT, kalsiyum ve protein.'),
            ('Pınar Süt Laktozsuz 1 L', 'Hassas sindirim, A vitamini.'),
            ('İçim Ayran 1 L', 'Geleneksel lezzet, soğuk içim.'),
            ('Coca-Cola 2.25 L Pet', 'Serinletici, parti ve sofra.'),
            ('Fruko Gazoz 1 L 6''lı Paket', 'Limon aromalı, nostaljik tat.'),
            ('Uludağ Limonata 1 L', 'Doğal limon suyu, şekerli.'),
            ('Çaykur Rize Turist Çayı 1000 g', 'Harman çay, demlik için.'),
            ('Doğuş Çayı Filiz 500 g', 'ince yaprak, aromatik.'),
            ('Mehmet Efendi Türk Kahvesi 250 g', 'Öğütülmüş, cezve için hazır.'),
            ('Nescafe Classic 200 g Kavanoz', 'Eko paket, hızlı kahve.'),
            ('Jacobs Monarch Filtre Kahve 250 g', 'Orta kavrum, French press uyumlu.'),
            ('Tchibo Exclusive Filtre Kahve 250 g', 'Premium harman, aroma zengin.'),
            ('Eti Cicibebe Bebek Bisküvisi 6''lı', 'Vitamin ve mineral takviyeli.'),
            ('Hero Baby Ek Gıda Elma Püresi 125 g', 'Katkısız, 4 ay+.'),
            ('Milupa 8 Tahıllı Mama 250 g', 'Gece maması, süt ile karıştırılır.'),
            ('Ebselen Omega 3 Balık Yağı 60 Kapsül', 'EPA/DHA, kalp ve beyin desteği.'),
            ('Supradyn Multivitamin 30 Tablet', 'Günlük vitamin ve mineral.'),
            ('Ocean Vitamin D3 400 IU Damla', 'Bebek ve çocuk için damla form.'),
            ('Solgar Vitamin C 1000 mg 100 Tablet', 'Bağışıklık desteği, yavaş salım.'),
            ('Imodium 2 mg İshal İlacı 12 Kapsül', 'Kısa süreli ishal, eczacıya danışın.'),
            ('Aspirin Protect 100 mg 30 Tablet', 'Kan sulandırıcı, reçeteli kullanım.'),
            ('Dolorex Fort Ağrı Kesici 20 Tablet', 'Baş ve kas ağrıları, yetişkin.'),
            ('Theraflu Grip ve Soğuk Algınlığı 10 Saşe', 'C vitamini ve sıcak içecek.'),
            ('Otrivin Burun Spreyi 10 ml', 'Tıkanıklık giderici, kısa süreli.'),
            ('Sterimar Deniz Suyu Burun Spreyi', 'Doğal, bebek ve yetişkin.'),
            ('Corega Diş Protez Temizleyici Tablet 30''lu', 'Gece bekletme, ferah nefes.'),
            ('Signal White Now Diş Macunu 75 ml', 'Anında beyazlık etkisi, florürlü.'),
            ('Colgate Total Diş Macunu 100 ml', '12 saat koruma, tam ağız.'),
            ('Oral-B Diş İpi 50 m', 'Nane aromalı, diş arası temizlik.'),
            ('Listerine Cool Mint Ağız Bakım Suyu 500 ml', 'Plak önleyici, ferah nefes.'),
            ('Head & Shoulders Şampuan 400 ml', 'Kepeğe karşı, klasik bakım.'),
            ('Pantene Onarıcı Şampuan 400 ml', 'Kırık uçlara karşı, keratin.'),
            ('Elidor Saç Kremi 500 ml', 'Yoğun nem, kolay tarama.'),
            ('Dove Güzellik Kremi Duş Jeli 500 ml', 'Nemlendirici krem tabaka.'),
            ('Nivea Erkek Roll-On 50 ml', '48 saat koruma, cilt dostu.'),
            ('Rexona Kadın Sprey 150 ml', 'Ter ve koku kontrolü, fresh.'),
            ('Gillette Fusion 5 Tıraş Bıçağı 4''lü Yedek', '5 bıçak, konforlu sürüş.'),
            ('Wilkinson Sword Hydro 3 Yedek Bıçak', 'Hareketli baş, ıslak tıraş.'),
            ('Schick Quattro Kadın Tıraç Bıçağı', '4 bıçak, nem şeridi.'),
            ('Veet Ağda Bandı Bacak 20''li', 'Hassas cilt, kolay uygulama.'),
            ('Nivea Erkek Traş Köpüğü 200 ml', 'Hassas cilt, yumuşak köpük.'),
            ('Gilette Series Traş Jeli 200 ml', 'Aloe vera, kayganlık.'),
            ('Komili Sıvı Yağ 2 L Ayçiçek', 'Kızartma ve salata için.'),
            ('Olin Ayçiçek Yağı 5 L Teneke', 'Ekonomik aile paketi.'),
            ('Sırma Zeytinyağı 1 L Riviera', 'Salata ve hafif kızartma.'),
            ('Kristal İyotlu Sofra Tuzu 750 g', 'İyot takviyesi, ince taneli.'),
            ('Billur Çankırı Tuzu 3 kg', 'Kaya tuzu, ekonomik kova.'),
            ('Arı Bakım Çiçek Balı 850 g', 'Süzme çiçek balı, doğal.'),
            ('Balparmak Süzme Çiçek Balı 460 g', 'Pratik sıkma kapak.'),
            ('Torku Pekmez 700 g', 'Üzüm pekmezi, demir kaynağı.'),
            ('Olin Pirinç 5 kg Osmancık', 'Pilav ve sütlaç için.'),
            ('Reis Pilavlık Bulgur 1 kg', 'Köftelik ince bulgur.'),
            ('Duru Bakliyat Mercimek 1 kg', 'Kırmızı mercimek, çorba ve yemek.'),
            ('Söke Un 5 kg', 'Börek ve ekmek için çok amaçlı.'),
            ('Pınar Labne 400 g', 'Kahvaltı ve tatlı süsleme.'),
            ('İçim Labne 180 g', 'Küçük aile boyu, krem kıvam.'),
            ('Eker Ayran 2 L', 'Restoran boyu, soğuk zincir.'),
            ('Sütaş Kaşar Peyniri 600 g', 'Tost ve kahvaltılık, dilimli.'),
            ('Pınar Beyaz Peynir 600 g', 'Tam yağlı, kahvaltı klasik.'),
            ('Torku Labne 400 g', 'Ekonomik alternatif, krem peynir.'),
            ('Eti Popkek 24''lü Kutu', 'Meyveli dolgulu, okul atıştırmalığı.'),
            ('Ülker Çokonat 24''lü', 'Fındıklı çikolata, nostalji.'),
            ('Eti Adicto 12''li', 'Karamelli bisküvi, kahve yanı.'),
            ('Ülker Halley Mini 10''lu', 'Tek porsiyon paketler.'),
            ('Eti Browni Intense 60 g', 'Yoğun çikolata, fırından tad.'),
            ('Ülker Metro 36''lı', 'Gofret ve çikolata, ekonomik kutu.'),
            ('Eti Cin 10''lu', 'Portakallı bisküvi, çay saati.'),
            ('Ülker 9 Kat Tat 24''lü', 'Katkısız gofret, ince katmanlar.'),
            ('Eti Burçak Yulaflı 10''lu', 'Lifli bisküvi, diyet dostu.'),
            ('Ülker Probis 10''lu', 'Protein bar tadında bisküvi.'),
            ('Eti Crax Peynirli 10''lu', 'Tuzlu kraker, aperatif.'),
            ('Ülker Çizi 12''li', 'Kıtır kraker, kahve yanı.'),
            ('Eti Gong 10''lu', 'Susamlı çubuk, hafif tuzlu.'),
            ('Ülker Halley King 6''lı', 'Büyük boy marshmallow.'),
            ('Eti Topkek 12''li', 'Meyveli muffin, kahvaltılık.'),
            ('Ülker Metro Gold 24''lü', 'Premium gofret serisi.'),
            ('Eti Canga King 24''lü', 'Büyük boy fındıklı bar.'),
            ('Ülker Albeni 24''lü', 'Karamel ve bisküvi, çocuk favorisi.'),
            ('Eti Adicto Max 8''li', 'Ekstra karamel dolgulu.'),
            ('Ülker Hobby 12''li', 'Çikolatalı bisküvi, klasik.'),
            ('Eti Brownini 6''lı', 'Mini brownie, tatlı kriz.'),
            ('Ülker Metro Mini 30''lu', 'Tek ısırık gofret.'),
            ('Eti Crax Stick 8''li', 'Uzun tuzlu çubuk.'),
            ('Ülker 8x8 24''lü', 'Kare gofret, paylaşımlı paket.'),
            ('Eti Burçak Sütlü 10''lu', 'Sütlü krema dolgulu.'),
            ('Ülker Çokomel 12''li', 'Sütlü çikolata kaplı.'),
            ('Eti Popkek Çilekli 24''lü', 'Meyve aromalı popkek.'),
            ('Ülker Halley Çilekli 10''lu', 'Çilek aromalı marshmallow.'),
            ('Eti Adicto Karamel 12''li', 'Ekstra karamel katmanı.'),
            ('Ülker Metro Fındıklı 24''lü', 'Fındık parçacıklı gofret.'),
            ('Eti Browni Gold 8''li', 'Altın sarısı paket, premium seri.'),
            ('Ülker Hobby Gold 12''lü', 'Altın ambalaj, sütlü çikolata.'),
            ('Eti Crax Pizza 10''lu', 'Pizza aromalı kraker.'),
            ('Ülker Çizi Peynirli 12''li', 'Peynir aromalı kraker.'),
            ('Eti Gong Susamlı 10''lu', 'Bol susam, çıtır.'),
            ('Ülker Probis Gold 10''lü', 'Altın seri protein bisküvi.'),
            ('Eti Topkek Çikolatalı 12''li', 'Çikolata damlacıklı muffin.'),
            ('Ülker Metro King 18''lü', 'King size gofret paketi.'),
            ('Eti Canga Gold 24''lü', 'Premium fındıklı bar.'),
            ('Ülker Albeni Max 18''lü', 'Büyük boy karamel bar.'),
            ('Eti Browni Double 6''lü', 'Çift çikolata katmanı.'),
            ('Ülker Hobby Max 10''lü', 'Büyük bisküvi, bol çikolata.'),
            ('Eti Crax Acılı 10''lu', 'Acılı kraker, atıştırmalık.'),
            ('Ülker Çizi Acılı 12''li', 'Baharatlı kraker.'),
            ('Eti Gong Peynirli 10''lu', 'Peynir aromalı çubuk.'),
            ('Ülker Metro Sütlü 24''lü', 'Sade sütlü gofret.'),
            ('Eti Popkek Muzlu 24''lü', 'Muz aromalı popkek.'),
            ('Ülker Halley Muzlu 10''lu', 'Muzlu marshmallow.'),
            ('Eti Adicto Fındıklı 12''li', 'Fındık parçacıklı karamel.'),
            ('Ülker Metro Antep Fıstıklı 24''lü', 'Antep fıstıklı premium gofret.')
    ) AS t(pname, pdesc)
    LIMIT 1 OFFSET (mod(g.n - 1, 160))
) AS v;

-- Ek kampanyalar (Trendyol / Hepsiburada tarzı vitrin)
INSERT INTO campaigns (title, subtitle, description, discount, image_url, background_color, time_left, button_text, button_href, start_date, end_date, is_active)
VALUES
    ('Süper Cuma Fırsatları', 'Elektronikte dev indirim', 'Telefon, TV ve küçük ev aletlerinde seçili ürünlerde ekstra indirim.', 45, 'https://picsum.photos/seed/sf1/800/320', '#f27a1a', '2 gün', 'Fırsatları gör', '/shop?sortBy=discount&sortOrder=desc', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '14 days', TRUE),
    ('Kış Lastiği Kampanyası', 'Oto & bahçe', '4 mevsim ve kış lastiklerinde montaj noktası önerileri ile birlikte.', 30, 'https://picsum.photos/seed/sf2/800/320', '#1e3a5f', '5 gün', 'Lastiklere git', '/shop?categoryId=17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '10 days', TRUE),
    ('Ev & yaşam haftası', 'Mobilya ve tekstil', 'Koltuk, yatak ve nevresimde sezon indirimi.', 35, 'https://picsum.photos/seed/sf3/800/320', '#7c3aed', '1 hafta', 'Keşfet', '/shop?categoryId=11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '7 days', TRUE),
    ('Anne & bebek günleri', 'Bebek bezinden mama sandalyesine', 'Seçili markalarda toplu alıma özel fiyatlar.', 25, 'https://picsum.photos/seed/sf4/800/320', '#ec4899', '3 gün', 'İncele', '/shop?categoryId=13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '5 days', TRUE),
    ('Süpermarket sepet dolusu', 'Gıda ve temizlik', 'Çok al az öde ürünlerinde ekstra indirim.', 20, 'https://picsum.photos/seed/sf5/800/320', '#059669', 'Sürekli', 'Alışverişe başla', '/shop?categoryId=15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '30 days', TRUE),
    ('Teknoloji günleri', 'Bilgisayar & tablet', 'Laptop, tablet ve aksesuarlarda kampanya.', 40, 'https://picsum.photos/seed/sf6/800/320', '#0ea5e9', '4 gün', 'Teknoloji', '/shop?categoryId=9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '8 days', TRUE);

-- Demo yorumlar (user id 2 = seed kullanıcı)
INSERT INTO reviews (rating, title, comment, is_verified, is_helpful, user_id, product_id, is_active, created_at, updated_at)
SELECT
    4 + (n % 2),
    CASE (n % 4) WHEN 0 THEN 'Harika' WHEN 1 THEN 'Fiyat performans' WHEN 2 THEN 'Hızlı kargo' ELSE 'Tavsiye ederim' END,
    'Ürün beklentimi karşıladı. Paketleme düzgün, kargo zamanında geldi. Tekrar alırım.',
    TRUE,
    (n % 3) = 0,
    2,
    n,
    TRUE,
    CURRENT_TIMESTAMP - (n * INTERVAL '1 day'),
    CURRENT_TIMESTAMP - (n * INTERVAL '1 day')
FROM generate_series(1, 40) AS n
WHERE EXISTS (SELECT 1 FROM products p WHERE p.id = n)
  AND NOT EXISTS (SELECT 1 FROM reviews r WHERE r.user_id = 2 AND r.product_id = n AND r.is_active = TRUE);
